---

urls:
  - https://www.dustinhome.no/product/5011062143/valueram
  - https://www.dustinhome.no/product/5011196312/geforce-rtx-3080-ventus-3x-oc-10gb
  - https://www.dustinhome.no/product/5011216707/geforce-rtx-3080-suprim-x-10gb
  - https://www.dustinhome.no/product/5011212484/geforce-rtx-3080-aorus-xtreme-waterforce-wb-10g
  - https://www.dustinhome.no/product/5011213213/geforce-rtx-3080-ftw3-ultra-hybrid-gaming-10gb
  - https://www.dustinhome.no/product/5011199977/geforce-rtx-3080-aorus-master-10gb
  - https://www.dustinhome.no/product/5011196138/geforce-rtx-3080-rog-strix-gaming-oc-10gb
  - https://www.dustinhome.no/product/5011197759/geforce-rtx-3080-ftw3-ultra-10gb
  - https://www.dustinhome.no/product/5011196313/geforce-rtx-3080-gaming-x-trio-10gb
  - https://www.dustinhome.no/product/5011213214/geforce-rtx-3080-xc3-ultra-hybrid-gaming-10gb
  - https://www.dustinhome.no/product/5011196137/geforce-rtx-3080-rog-strix-gaming-10gb
  - https://www.dustinhome.no/product/5011196307/geforce-rtx-3080-eagle-oc-10gb
  - https://www.dustinhome.no/product/5011197756/geforce-rtx-3080-xc3-ultra-10gb
  - https://www.dustinhome.no/product/5011195967/geforce-rtx-3080-tuf-gaming-10gb
  - https://www.dustinhome.no/product/5011195968/geforce-rtx-3080-tuf-gaming-oc-10gb
  - https://www.dustinhome.no/product/5011199976/geforce-rtx-3080-vision-10gb
  - https://www.dustinhome.no/product/5011197757/geforce-rtx-3080-xc3-black-10gb
  - https://www.dustinhome.no/product/5011197760/geforce-rtx-3080-ftw3-10gb
  - https://www.dustinhome.no/product/5011197758/geforce-rtx-3080-xc3-10gb
  - https://www.dustinhome.no/product/5011196134/geforce-rtx-3080-10gb-xlr8-gaming-epic-x-rgb
  - https://www.dustinhome.no/product/5011196306/geforce-rtx-3080-gaming-oc-10gb
  - https://www.dustinhome.no/product/5011196133/geforce-rtx-3080-10gb-xlr8-gaming-epic-x-rgb
...
