---

urls:
  - https://www.komplett.no/product/1168415/datautstyr/pc-komponenter/skjermkort/gigabyte-geforce-rtx-3080-eagle-oc
  - https://www.komplett.no/product/1171801/datautstyr/pc-komponenter/skjermkort/gainward-geforce-rtx-3080-phantom-gs
  - https://www.komplett.no/product/1168418/datautstyr/pc-komponenter/skjermkort/gigabyte-geforce-rtx-3080-aorus-master
  - https://www.komplett.no/product/1171798/datautstyr/pc-komponenter/skjermkort/gainward-geforce-rtx-3080-phantom
  - https://www.komplett.no/product/1168380/datautstyr/pc-komponenter/skjermkort/msi-geforce-rtx-3080-gaming-x-trio
  - https://www.komplett.no/product/1173669/datautstyr/pc-komponenter/skjermkort/msi-geforce-rtx-3080-suprim-x
  - https://www.komplett.no/product/1168419/datautstyr/pc-komponenter/skjermkort/gigabyte-geforce-rtx-3080-gaming-oc
  - https://www.komplett.no/product/1171562/datautstyr/pc-komponenter/skjermkort/gigabyte-geforce-rtx-3080-vision-oc
  - https://www.komplett.no/product/1170425/datautstyr/pc-komponenter/skjermkort/zotac-geforce-rtx-3080-amp-holo
  - https://www.komplett.no/product/1168358/datautstyr/pc-komponenter/skjermkort/asus-geforce-rtx-3080-tuf-gaming
  - https://www.komplett.no/product/1170423/datautstyr/pc-komponenter/skjermkort/zotac-geforce-rtx-3080-trinity-oc
  - https://www.komplett.no/product/1168379/datautstyr/pc-komponenter/skjermkort/msi-geforce-rtx-3080-ventus-3x-oc
  - https://www.komplett.no/product/1168436/datautstyr/pc-komponenter/skjermkort/asus-geforce-rtx-3080-rog-strix-oc
  - https://www.komplett.no/product/1168398/datautstyr/pc-komponenter/skjermkort/zotac-geforce-rtx-3080-trinity
  - https://www.komplett.no/product/1168439/datautstyr/pc-komponenter/skjermkort/asus-geforce-rtx-3080-rog-strix
  - https://www.komplett.no/product/1176247/datautstyr/pc-komponenter/skjermkort/asus-geforce-rtx-3080-rog-strix-oc-white
  - https://www.komplett.no/product/1168425/datautstyr/pc-komponenter/skjermkort/palit-geforce-rtx-3080-gamingpro-oc
  - https://www.komplett.no/product/1171797/datautstyr/pc-komponenter/skjermkort/palit-geforce-rtx-3080-gamerock-oc
  - https://www.komplett.no/product/1174235/datautstyr/pc-komponenter/skjermkort/asus-geforce-rtx-3080-ek
  - https://www.komplett.no/product/1168422/datautstyr/pc-komponenter/skjermkort/gainward-geforce-rtx-3080-phoenix-gs
  - https://www.komplett.no/product/1168128/datautstyr/pc-komponenter/skjermkort/palit-geforce-rtx-3080-gamingpro
  - https://www.komplett.no/product/1168416/datautstyr/pc-komponenter/skjermkort/gigabyte-geforce-rtx-3080-aorus-xtreme
  - https://www.komplett.no/product/1168129/datautstyr/pc-komponenter/skjermkort/gainward-geforce-rtx-3080-phoenix
  - https://www.komplett.no/product/1175704/datautstyr/pc-komponenter/skjermkort/gigabyte-geforce-rtx-3080-aorus-xtreme-wf
  - https://www.komplett.no/product/1175718/datautstyr/pc-komponenter/skjermkort/gigabyte-geforce-rtx-3080-eagle
...
