---

urls:
  - https://www.multicom.no/gigabyte-geforce-rtx-3070-eagle/cat-p/c100134/p1001473456
  - https://www.multicom.no/gigabyte-geforce-rtx-3070-gaming/cat-p/c100134/p1001473455
  - https://www.multicom.no/msi-rtx-3070-ventus-3x/cat-p/c100134/p1001503071
  - https://www.multicom.no/zotac-gaming-geforce-rtx-3070/cat-p/c100134/p1001456156
  - https://www.multicom.no/msi-geforce-rtx-3070-gaming/cat-p/c100134/p1001503070
  - https://www.multicom.no/msi-rtx-3070-ventus-2x/cat-p/c100134/p1001503072
  - https://www.multicom.no/zotac-gaming-geforce-rtx-3070/cat-p/c100134/p1001467976
  - https://www.multicom.no/asus-rog-strix-rtx3070-o8g-white-oc-edition-grafikkort/cat-p/c100134/p1001547460
  - https://www.multicom.no/inno3d-geforce-rtx-3070-8gb/cat-p/c100134/p1001501648
  - https://www.multicom.no/zotac-gaming-geforce-rtx-3070/cat-p/c100134/p1001545723
  - https://www.multicom.no/asus-dual-rtx3070-8g-grafikkort-gf-rtx/cat-p/c100134/p1001453116
  - https://www.multicom.no/msi-geforce-rtx-3070-suprim/cat-p/c100134/p1001541399
  - https://www.multicom.no/asus-rog-strix-rtx3070-8g-white-grafikkort-gf-rtx/cat-p/c100134/p1001547461
  - https://www.multicom.no/pny-xlr8-geforce-rtx-3070/cat-p/c100134/p1001506149
  - https://www.multicom.no/inno3d-geforce-rtx-3070-8gb/cat-p/c100134/p1001501647
  - https://www.multicom.no/msi-rtx-3070-suprim-8g/cat-p/c100134/p1001572688
  - https://www.multicom.no/asus-tuf-rtx3070-o8g-gaming-grafikkort-gf-rtx/cat-p/c100134/p1001491549
  - https://www.multicom.no/pny-geforce-rtx-3070-dual/cat-p/c100134/p1001506150
  - https://www.multicom.no/inno3d-geforce-rtx-3070-8gb/cat-p/c100134/p1001501646
  - https://www.multicom.no/asus-rog-strix-rtx3070-o8g-gaming-grafikkort-gf-rtx/cat-p/c100134/p1001460875
  - https://www.multicom.no/asus-dual-rtx3070-o8g-oc-edition-grafikkort/cat-p/c100134/p1001505106
  - https://www.multicom.no/asus-tuf-rtx3070-8g-gaming-grafikkort-gf-rtx/cat-p/c100134/p1001491550
  - https://www.multicom.no/asus-rog-strix-rtx3070-8g-gaming-grafikkort-gf-rtx/cat-p/c100134/p1001503069
  - https://www.multicom.no/zotac-gaming-geforce-rtx-3070/cat-p/c100134/p1001557254
  - https://www.multicom.no/asus-rtx3070-8g-ek-grafikkort-gf-rtx/cat-p/c100134/p1001547462
...
