---

urls:
  - https://www.multicom.no/asus-geforce-rtx-3080-10gb/cat-p/c/p1001439690
  - https://www.multicom.no/asus-geforce-rtx-3080-10gb/cat-p/c/p1001439691
  - https://www.multicom.no/gigabyte-geforce-rtx-3080-10gb/cat-p/c/p1001437238
  - https://www.multicom.no/gigabyte-geforce-rtx-3080-10gb/cat-p/c/p1001437239
  - https://www.multicom.no/gigabyte-geforce-rtx-3080-eagle/cat-p/c/p1001473457
  - https://www.multicom.no/gigabyte-aorus-geforce-rtx-3080/cat-p/c/p1001457081
  - https://www.multicom.no/inno3d-geforce-rtx-3080-10gb/cat-p/c/p1001518239
  - https://www.multicom.no/inno3d-geforce-rtx-3080-10gb/cat-p/c/p1001440890
...
