---

urls:
  - https://www.multicom.no/gigabyte-geforce-rtx-3060-ti/cat-p/c100134/p1001552330
  - https://www.multicom.no/gigabyte-geforce-rtx-3060-ti/cat-p/c100134/p1001550187
  - https://www.multicom.no/zotac-gaming-geforce-rtx-3060/cat-p/c100134/p1001552339
  - https://www.multicom.no/asus-dual-rtx3060ti-8g-grafikkort-gf-rtx/cat-p/c100134/p1001552232
  - https://www.multicom.no/asus-rog-strix-rtx3060ti-o8g-gaming-oc-edition-grafikkort/cat-p/c100134/p1001552233
  - https://www.multicom.no/msi-geforce-rtx-3060-ti/cat-p/c100134/p1001552336
  - https://www.multicom.no/msi-rtx-3060-ti-gaming/cat-p/c100134/p1001596442
  - https://www.multicom.no/msi-geforce-rtx-3060-ti/cat-p/c100134/p1001552337
  - https://www.multicom.no/asus-tuf-rtx3060ti-o8g-gaming-oc-edition-grafikkort/cat-p/c100134/p1001547543
  - https://www.multicom.no/asus-dual-rtx3060ti-o8g-oc-edition-grafikkort/cat-p/c100134/p1001552231
  - https://www.multicom.no/asus-tuf-rtx3060ti-8g-gaming-grafikkort-gf-rtx/cat-p/c100134/p1001552230
  - https://www.multicom.no/asus-rog-strix-rtx3060ti-8g-gaming-grafikkort-gf-rtx/cat-p/c100134/p1001552234
  - https://www.multicom.no/asus-dual-rtx3060ti-8g-mini-grafikkort-gf-rtx/cat-p/c100134/p1001572825
  - https://www.multicom.no/asus-dual-rtx3060ti-o8g-mini-oc-edition-grafikkort/cat-p/c100134/p1001572826
  - https://www.multicom.no/inno3d-geforce-rtx-3060-ti/cat-p/c100134/p1001550185
  - https://www.multicom.no/inno3d-geforce-rtx-3060-ti/cat-p/c100134/p1001550186
...
