---

urls:
  - https://www.multicom.no/msi-rtx-3080-suprim-x/cat-p/c100134/p1001547471
  - https://www.multicom.no/asus-tuf-rtx3080-10g-gaming-grafikkort-gf-rtx/cat-p/c100134/p1001439753
  - https://www.multicom.no/zotac-gaming-geforce-rtx-3080/cat-p/c100134/p1001440871
  - https://www.multicom.no/pny-xlr8-geforce-rtx-3080/cat-p/c100134/p1001440879
  - https://www.multicom.no/gainward-geforce-rtx-3080-phoenix/cat-p/c100134/p1001441689
  - https://www.multicom.no/asus-rog-strix-rtx3080-o10g-white-oc-edition-grafikkort/cat-p/c100134/p1001547468
  - https://www.multicom.no/zotac-gaming-geforce-rtx-3080/cat-p/c100134/p1001440873
  - https://www.multicom.no/asus-rog-strix-rtx3080-10g-white-grafikkort-gf-rtx/cat-p/c100134/p1001547470
  - https://www.multicom.no/gigabyte-geforce-rtx-3080-vision/cat-p/c100134/p1001457887
  - https://www.multicom.no/asus-rtx3080-10g-ek-grafikkort-gf-rtx/cat-p/c100134/p1001518226
  - https://www.multicom.no/asus-turbo-rtx3080-10g-grafikkort-gf-rtx/cat-p/c100134/p1001603429
  - https://www.multicom.no/msi-geforce-rtx-3080-gaming/cat-p/c100134/p1001440885
  - https://www.multicom.no/msi-geforce-rtx-3080-suprim/cat-p/c100134/p1001547471
...
