---

urls:
  - https://www.netonnet.no/art/datakomponenter/skjermkort/nvidia/asus-geforce-rtx-3060ti-rog-strix-gaming-8gb/1015572.11111/
  - https://www.netonnet.no/art/datakomponenter/skjermkort/nvidia/msi-geforce-rtx-3060-ti-gaming-x-trio/1015906.11111/
  - https://www.netonnet.no/art/datakomponenter/skjermkort/nvidia/asus-geforce-rtx-3060ti-tuf-gaming-oc-8gb/1015565.11111/
  - https://www.netonnet.no/art/datakomponenter/skjermkort/nvidia/gigabyte-geforce-rtx-3060-ti-eagle-8g/1015575.11111/
  - https://www.netonnet.no/art/datakomponenter/skjermkort/nvidia/gigabyte-geforce-rtx-3060-ti-aorus-master/1015582.11111/
  - https://www.netonnet.no/art/datakomponenter/skjermkort/nvidia/asus-geforce-rtx-3060ti-dual-oc-8gb/1015673.11111/
  - https://www.netonnet.no/art/datakomponenter/skjermkort/nvidia/gigabyte-geforce-rtx-3060ti-gaming-pro-oc/1016888.11111/
  - https://www.netonnet.no/art/datakomponenter/skjermkort/nvidia/asus-geforce-rtx-3060-ti-rog-strix-gaming-oc-8gb/1016449.11111/
  - https://www.netonnet.no/art/datakomponenter/skjermkort/nvidia/gigabyte-geforce-rtx-3060-ti-gaming-oc-8gb/1015578.11111/
  - https://www.netonnet.no/art/datakomponenter/skjermkort/nvidia/gigabyte-geforce-rtx-3060-ti-eagle-oc-8g/1015576.11111/
  - https://www.netonnet.no/art/datakomponenter/skjermkort/nvidia/msi-geforce-gtx-3060ti-gaming-x/1017017.11111/
...
