---

urls:
  - https://www.netonnet.no/art/datakomponenter/skjermkort/nvidia/msi-geforce-rtx-3070-ventus-2x-oc/1014370.11111/
  - https://www.netonnet.no/art/datakomponenter/skjermkort/nvidia/asus-geforce-rtx-3070-tuf-gaming/1014925.11111/
  - https://www.netonnet.no/art/datakomponenter/skjermkort/nvidia/gigabyte-geforce-rtx-3070-eagle-oc-8g/1014993.11111/
  - https://www.netonnet.no/art/datakomponenter/skjermkort/nvidia/gigabyte-geforce-rtx-3070-master-8gb/1016319.11111/
  - https://www.netonnet.no/art/datakomponenter/skjermkort/nvidia/asus-geforce-rtx-3070-rog-strix-gaming-oc-8gb/1016448.11111/
  - https://www.netonnet.no/art/datakomponenter/skjermkort/nvidia/msi-geforce-rtx-3070-suprim-8g/1016112.11111/
  - https://www.netonnet.no/art/datakomponenter/skjermkort/nvidia/gigabyte-geforce-rtx-3070-vision-oc-8gb/1015511.11111/
  - https://www.netonnet.no/art/datakomponenter/skjermkort/nvidia/asus-geforce-rtx-3070-tuf-gaming-oc-8gb/1015672.11111/
  - https://www.netonnet.no/art/datakomponenter/skjermkort/nvidia/asus-geforce-rtx-3070-dual-oc-8gb/1015671.11111/
  - https://www.netonnet.no/art/datakomponenter/skjermkort/nvidia/msi-geforce-rtx-3070-suprim-x-8g/1015718.11111/
...
