---

urls:
  - https://www.netonnet.no/art/datakomponenter/skjermkort/nvidia/gigabyte-geforce-rtx-3080-aorus-xtream-10gb/1015517.11111/
  - https://www.netonnet.no/art/datakomponenter/skjermkort/nvidia/asus-geforce-rtx-3080-rog-strix-gaming-10g/1014394.11111/
  - https://www.netonnet.no/art/datakomponenter/skjermkort/nvidia/asus-geforce-rtx-3080-rog-strix-gaming-oc-white-10gb/1015992.11111/
  - https://www.netonnet.no/art/datakomponenter/skjermkort/nvidia/asus-geforce-rtx-3080-rog-strix-gaming-oc-10gb/1016281.11111/
  - https://www.netonnet.no/art/datakomponenter/skjermkort/nvidia/asus-geforce-rtx-3080-tuf-gaming-10g/1014354.11111/
  - https://www.netonnet.no/art/datakomponenter/skjermkort/nvidia/asus-geforce-rtx-3080-tuf-gaming-oc-10gb/1015670.11111/
  - https://www.netonnet.no/art/datakomponenter/skjermkort/nvidia/msi-geforce-rtx-3080-gaming-x-trio-10g/1014373.11111/
  - https://www.netonnet.no/art/datakomponenter/skjermkort/nvidia/gigabyte-geforce-rtx-3080-gaming-oc-10g/1014380.11111/
  - https://www.netonnet.no/art/datakomponenter/skjermkort/nvidia/gigabyte-geforce-rtx-3080-eagle-oc-10g/1014382.11111/
  - https://www.netonnet.no/art/datakomponenter/skjermkort/nvidia/msi-geforce-rtx-3080-ventus-3x-10g-oc/1014374.11111/
  - https://www.netonnet.no/art/datakomponenter/skjermkort/nvidia/msi-geforce-rtx-3080-suprim-x-10g/1015474.11111/
...
