---

urls:
  - https://www.proshop.no/Grafikkort/ASUS-GeForce-RTX-3080-TUF-10GB-GDDR6X-RAM-Grafikkort/2876763
  - https://www.proshop.no/Grafikkort/ASUS-GeForce-RTX-3080-ROG-STRIX-OC-10GB-GDDR6X-RAM-Grafikkort/2876859
  - https://www.proshop.no/Grafikkort/MSI-GeForce-RTX-3080-SUPRIM-X-10GB-GDDR6X-RAM-Grafikkort/2885270
  - https://www.proshop.no/Grafikkort/MSI-GeForce-RTX-3080-GAMING-X-TRIO-10GB-GDDR6X-RAM-Grafikkort/2876877
  - https://www.proshop.no/Grafikkort/ASUS-GeForce-RTX-3080-ROG-STRIX-OC-White-10GB-GDDR6X-RAM-Grafikkort/2911579
  - https://www.proshop.no/Grafikkort/Inno3D-GeForce-RTX-3080-Twin-X2-OC-10GB-GDDR6X-RAM-Grafikkort/2878968
  - https://www.proshop.no/Grafikkort/ASUS-GeForce-RTX-3080-TUF-OC-10GB-GDDR6X-RAM-Grafikkort/2876861
  - https://www.proshop.no/Grafikkort/GIGABYTE-GeForce-RTX-3080-GAMING-OC-10GB-GDDR6X-RAM-Grafikkort/2876838
  - https://www.proshop.no/Grafikkort/Inno3D-GeForce-RTX-3080-iCHILL-X3-10GB-GDDR6X-RAM-Grafikkort/2878969
  - https://www.proshop.no/Grafikkort/GIGABYTE-GeForce-RTX-3080-AORUS-Xtreme-10GB-GDDR6X-RAM-Grafikkort/2876836
  - https://www.proshop.no/Grafikkort/MSI-GeForce-RTX-3080-VENTUS-3X-OC-10GB-GDDR6X-RAM-Grafikkort/2876879
  - https://www.proshop.no/Grafikkort/GIGABYTE-GeForce-RTX-3080-Vision-OC-10GB-GDDR6X-RAM-Grafikkort/2878401
  - https://www.proshop.no/Grafikkort/Inno3D-GeForce-RTX-3080-iCHILL-Frostbite-10GB-GDDR6X-RAM-Grafikkort/2887321
  - https://www.proshop.no/Grafikkort/ASUS-GeForce-RTX-3080-EK-10GB-GDDR6X-RAM-Grafikkort/2887568
  - https://www.proshop.no/Grafikkort/GIGABYTE-GeForce-RTX-3080-AORUS-Master-10GB-GDDR6X-RAM-Grafikkort/2876835
  - https://www.proshop.no/Grafikkort/ASUS-GeForce-RTX-3080-ROG-STRIX-10GB-GDDR6X-RAM-Grafikkort/2876857
  - https://www.proshop.no/Grafikkort/GIGABYTE-GeForce-RTX-3080-Eagle-OC-10GB-GDDR6X-RAM-Grafikkort/2876837
  - https://www.proshop.no/Grafikkort/GIGABYTE-GeForce-RTX-3080-AORUS-WaterForce-Xtreme-10GB-GDDR6X-RAM-Grafikkort/2878393
  - https://www.proshop.no/Grafikkort/ASUS-GeForce-RTX-3080-ROG-STRIX-White-10GB-GDDR6X-RAM-Grafikkort/2911578
  - https://www.proshop.no/Grafikkort/GIGABYTE-GeForce-RTX-3080-Eagle-10GB-GDDR6X-RAM-Grafikkort/2878395
  - https://www.proshop.no/Grafikkort/GIGABYTE-GeForce-RTX-3080-AORUS-WaterForce-WB-Xtreme-10GB-GDDR6X-RAM-Grafikkort/2878394
  - https://www.proshop.no/Grafikkort/Inno3D-GeForce-RTX-3080-iCHILL-X4-10GB-GDDR6X-RAM-Grafikkort/2878971
...
